# Data Cleaning

## Bharat Bazaar Intelligence Platform (BBIP)

### Phase 2: Data Cleaning & Preprocessing

Data cleaning is one of the most critical phases in the data analytics lifecycle. The quality of business insights depends heavily on the quality of the underlying data.

In this notebook, we will identify and resolve data quality issues such as missing values, duplicate records, incorrect data types, inconsistent values, and invalid business records. The cleaned dataset produced in this phase will serve as the foundation for SQL analysis, exploratory data analysis (EDA), machine learning, and Power BI dashboard development.

# Business Objectives

The objectives of this notebook are:

- Evaluate overall data quality.
- Detect and handle missing values.
- Identify duplicate records.
- Validate data types.
- Check for invalid business values.
- Standardize data where necessary.
- Prepare a clean dataset for downstream analytics.
- Export the cleaned dataset for SQL, EDA, Machine Learning, and Dashboard development.

# Import Required Libraries

The following libraries are required for data cleaning and preprocessing.

In [105]:
# Import required libraries

import pandas as pd
import numpy as np

# Load Raw Dataset

Load the raw Global E-Commerce Sales dataset for data quality assessment and preprocessing.

In [106]:
# Load dataset

df = pd.read_csv("../data/raw/global_ecommerce_sales.csv")

# Preview Dataset

Display the first few records to verify that the dataset has been loaded successfully.

In [107]:
# Display first five rows

df.head()

,Order_ID,Order_Date,Customer_Name,Customer_Segment,Country,Region,Product_Category,Product_Name,Quantity,Unit_Price,Discount_Percent,Total_Sales,Shipping_Cost,Profit,Payment_Method
0,ORD-11121,2023-01-02,Karen Suzuki,Corporate,United States,North America,Technology,Wireless Bluetooth Headphones,3,99.43,0,298.29,9.31,124.92,Cash on Delivery
1,ORD-11244,2023-01-02,John Johansson,Corporate,Spain,Europe,Technology,Mechanical Gaming Keyboard,4,97.93,20,313.38,14.31,83.62,Cash on Delivery
2,ORD-10325,2023-01-03,Jessica Garcia,Consumer,Mexico,North America,Office Supplies,Binder Clips Assorted 48pc,2,10.74,0,21.48,8.12,3.69,Credit Card
3,ORD-10467,2023-01-03,Clara Taylor,Corporate,Italy,Europe,Technology,Webcam HD 1080p,2,61.86,15,105.16,10.79,26.32,PayPal
4,ORD-11454,2023-01-05,Felix Thomas,Consumer,Italy,Europe,Furniture,Standing Desk Converter,4,330.67,20,1058.14,11.09,253.44,Credit Card

# Business Observation

The dataset has been loaded successfully. The preview provides an initial understanding of the available business attributes, including customer details, product information, sales, profit, shipping cost, and payment methods. These attributes will now undergo systematic quality assessment before analysis.

# Data Quality Assessment

Before cleaning the dataset, it is important to evaluate its overall quality. This includes checking the dataset structure, missing values, duplicate records, data types, and memory usage.

In [108]:
# Display dataset dimensions

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

Rows    : 2000
Columns : 15

# Business Observation

The dataset dimensions indicate the total number of business transactions and attributes available for analysis. This helps estimate the scope of the cleaning process.

In [109]:
# Display dataset information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          2000 non-null   str
 1   Order_Date        2000 non-null   str
 2   Customer_Name     2000 non-null   str
 3   Customer_Segment  2000 non-null   str
 4   Country           2000 non-null   str
 5   Region            2000 non-null   str
 6   Product_Category  2000 non-null   str
 7   Product_Name      2000 non-null   str
 8   Quantity          2000 non-null   int64
 9   Unit_Price        2000 non-null   float64
 10  Discount_Percent  2000 non-null   int64
 11  Total_Sales       2000 non-null   float64
 12  Shipping_Cost     2000 non-null   float64
 13  Profit            2000 non-null   float64
 14  Payment_Method    2000 non-null   str
dtypes: float64(4), int64(2), str(9)
memory usage: 440.1 KB

# Business Observation

The dataset information provides details about column names, data types, and non-null values. This helps identify columns that may require cleaning or data type conversion.

In [110]:
# Check missing values

missing_values = df.isnull().sum()
missing_values

Order_ID            0
Order_Date          0
Customer_Name       0
Customer_Segment    0
Country             0
Region              0
Product_Category    0
Product_Name        0
Quantity            0
Unit_Price          0
Discount_Percent    0
Total_Sales         0
Shipping_Cost       0
Profit              0
Payment_Method      0
dtype: int64

# Business Observation

Missing values can reduce the quality of business insights. Identifying them early helps determine the appropriate cleaning strategy, such as imputation or record removal.

In [111]:
# Check duplicate records

duplicate_count = df.duplicated().sum()
print("Duplicate Records:", duplicate_count)

Duplicate Records: 0

# Business Observation

Duplicate transactions can distort sales, profit, and customer metrics. Detecting duplicate records is essential for maintaining data integrity.

In [112]:
# Check memory usage

df.memory_usage(deep=True)

Index                 132
Order_ID            34000
Order_Date          36000
Customer_Name       40227
Customer_Segment    33736
Country             31467
Region              39415
Product_Category    43014
Product_Name        59577
Quantity            16000
Unit_Price          16000
Discount_Percent    16000
Total_Sales         16000
Shipping_Cost       16000
Profit              16000
Payment_Method      37046
dtype: int64

# Business Observation

Memory usage analysis helps evaluate the efficiency of the dataset and becomes increasingly important when processing larger retail datasets.

# Missing Value Analysis

Missing values can reduce data quality and negatively impact business insights, SQL queries, dashboards, and machine learning models.

This section identifies missing values, measures their impact, and applies an appropriate treatment strategy.

In [113]:
# Count missing values in each column

missing_values = df.isnull().sum()

missing_values

Order_ID            0
Order_Date          0
Customer_Name       0
Customer_Segment    0
Country             0
Region              0
Product_Category    0
Product_Name        0
Quantity            0
Unit_Price          0
Discount_Percent    0
Total_Sales         0
Shipping_Cost       0
Profit              0
Payment_Method      0
dtype: int64

# Business Observation

The above output shows the number of missing values present in each feature. Columns with missing values require further investigation before deciding whether to remove or impute them.

In [114]:
# Calculate missing value percentage

missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_df = pd.DataFrame({
    "Missing Values": missing_values,
    "Percentage (%)": missing_percentage.round(2)
})

missing_df

                  Missing Values  Percentage (%)
Order_ID                       0             0.0
Order_Date                     0             0.0
Customer_Name                  0             0.0
Customer_Segment               0             0.0
Country                        0             0.0
Region                         0             0.0
Product_Category               0             0.0
Product_Name                   0             0.0
Quantity                       0             0.0
Unit_Price                     0             0.0
Discount_Percent               0             0.0
Total_Sales                    0             0.0
Shipping_Cost                  0             0.0
Profit                         0             0.0
Payment_Method                 0             0.0

# Business Observation

The percentage of missing values helps determine the most appropriate cleaning strategy. Features with a very small percentage of missing values can often be cleaned without significantly affecting business analysis.

In [115]:
# Display only columns containing missing values

missing_df[missing_df["Missing Values"] > 0]

Empty DataFrame
Columns: [Missing Values, Percentage (%)]
Index: []

# Business Observation

This filtered view highlights only the columns that require attention, allowing the cleaning process to focus on relevant business attributes.

In [116]:
# Create a backup before applying any cleaning

df_clean = df.copy()

# Cleaning Strategy

A backup copy of the dataset has been created before applying any cleaning operations. This ensures that the original raw dataset remains unchanged and allows the cleaning process to be reproduced safely.

In [117]:
# Verify whether missing values exist

if missing_values.sum() == 0:
    print("✅ No missing values found in the dataset.")
else:
    print("⚠ Missing values detected.")

✅ No missing values found in the dataset.

# Business Observation

The dataset has now been evaluated for missing values. If missing values are present, they will be handled using appropriate business-driven methods. If no missing values exist, no further action is required for this step.

# Duplicate Record Analysis

Duplicate records can distort business metrics such as total sales, profit, customer count, and product performance.

This section identifies duplicate transactions and removes them if necessary to ensure data integrity.

In [118]:
# Count duplicate records

duplicate_count = df_clean.duplicated().sum()

print(f"Duplicate Records Found: {duplicate_count}")

Duplicate Records Found: 0

# Business Observation

Duplicate records represent repeated transactions and may lead to inaccurate reporting. Identifying them before analysis ensures reliable business insights.

In [119]:
# Display duplicate rows (if any)

duplicate_rows = df_clean[df_clean.duplicated()]

duplicate_rows.head()

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_Name, Customer_Segment, Country, Region, Product_Category, Product_Name, Quantity, Unit_Price, Discount_Percent, Total_Sales, Shipping_Cost, Profit, Payment_Method]
Index: []

# Business Observation

Reviewing duplicate records helps determine whether they are true duplicates or legitimate repeated business transactions before deciding to remove them.

In [120]:
# Remove duplicate records

df_clean = df_clean.drop_duplicates()

In [121]:
# Verify duplicate removal

print("Remaining Duplicate Records:", df_clean.duplicated().sum())

Remaining Duplicate Records: 0

# Business Observation

Duplicate records have been removed successfully (if present). The cleaned dataset now contains only unique business transactions, improving the accuracy of future analysis and reporting.

In [122]:
# Compare dataset size after duplicate removal

print("Dataset Shape After Cleaning:", df_clean.shape)

Dataset Shape After Cleaning: (2000, 15)

# Cleaning Summary

The duplicate analysis confirms that the dataset has been checked for repeated records. Any duplicate entries have been removed, ensuring higher data quality and more trustworthy business insights.

# Data Type Validation

Correct data types are essential for accurate business analysis. In this section, we validate and standardize the data types of all features to ensure compatibility with SQL analysis, exploratory data analysis (EDA), machine learning, and Power BI dashboards.

In [123]:
# Display current data types

df_clean.dtypes

Order_ID                str
Order_Date              str
Customer_Name           str
Customer_Segment        str
Country                 str
Region                  str
Product_Category        str
Product_Name            str
Quantity              int64
Unit_Price          float64
Discount_Percent      int64
Total_Sales         float64
Shipping_Cost       float64
Profit              float64
Payment_Method          str
dtype: object

# Business Observation

Reviewing the current data types helps identify columns that may require conversion. For example, date fields should use datetime format, while sales and profit fields should remain numeric for calculations.

In [124]:
# Convert Order_Date to datetime

df_clean["Order_Date"] = pd.to_datetime(
    df_clean["Order_Date"],
    errors="coerce"
)

# Business Observation

The `Order_Date` column has been converted into datetime format, enabling time-based analyses such as monthly sales trends, seasonal performance, and year-over-year comparisons.

In [125]:
# Verify updated data types

df_clean.dtypes

Order_ID                       str
Order_Date          datetime64[us]
Customer_Name                  str
Customer_Segment               str
Country                        str
Region                         str
Product_Category               str
Product_Name                   str
Quantity                     int64
Unit_Price                 float64
Discount_Percent             int64
Total_Sales                float64
Shipping_Cost              float64
Profit                     float64
Payment_Method                 str
dtype: object

In [126]:
# Check for invalid dates after conversion

invalid_dates = df_clean["Order_Date"].isnull().sum()

print(f"Invalid Dates Found: {invalid_dates}")

Invalid Dates Found: 0

# Business Observation

Any invalid date values are automatically converted to `NaT` (Not a Time). These records can be investigated further before performing time-series analysis.

In [127]:
# Display numerical columns

df_clean.select_dtypes(include=["int64", "float64"]).columns

Index(['Quantity', 'Unit_Price', 'Discount_Percent', 'Total_Sales',
       'Shipping_Cost', 'Profit'],
      dtype='str')

# Data Type Validation Summary

The dataset has been validated for appropriate data types. Date fields are now stored correctly, and numerical features are ready for statistical analysis, SQL queries, machine learning models, and interactive dashboards.

# Business Rule Validation

Business rule validation ensures that the dataset follows logical business constraints. Invalid records can negatively affect reports, dashboards, forecasts, and business decisions.

In this section, we validate important business rules for retail transactions.

In [128]:
# Check for invalid quantity values

invalid_quantity = df_clean[df_clean["Quantity"] <= 0]

print("Invalid Quantity Records:", len(invalid_quantity))

Invalid Quantity Records: 0

# Business Observation

Product quantity should always be greater than zero. Transactions with zero or negative quantities indicate invalid business records.

In [129]:
# Check for invalid unit prices

invalid_price = df_clean[df_clean["Unit_Price"] <= 0]

print("Invalid Unit Price Records:", len(invalid_price))

Invalid Unit Price Records: 0

# Business Observation

Products cannot have zero or negative selling prices. These records should be investigated before performing revenue analysis.

In [130]:
# Check for invalid shipping costs

invalid_shipping = df_clean[df_clean["Shipping_Cost"] < 0]

print("Invalid Shipping Cost Records:", len(invalid_shipping))

Invalid Shipping Cost Records: 0

# Business Observation

Shipping costs should never be negative. Negative values usually indicate data entry or system errors.

In [131]:
# Validate discount percentage

invalid_discount = df_clean[
    (df_clean["Discount_Percent"] < 0) |
    (df_clean["Discount_Percent"] > 100)
]

print("Invalid Discount Records:", len(invalid_discount))

Invalid Discount Records: 0

# Business Observation

Discount percentages should fall between 0% and 100%. Values outside this range are considered invalid.

In [132]:
# Check for negative sales

invalid_sales = df_clean[df_clean["Total_Sales"] < 0]

print("Negative Sales Records:", len(invalid_sales))

Negative Sales Records: 0

# Business Observation

Sales revenue should not be negative. Negative sales values may indicate data inconsistencies.

In [133]:
# Check future order dates

today = pd.Timestamp.today()

future_orders = df_clean[df_clean["Order_Date"] > today]

print("Future Order Records:", len(future_orders))

Future Order Records: 0

# Business Observation

Order dates should not occur in the future. Future-dated transactions should be verified before analysis.

In [134]:
# Overall validation summary

validation_summary = pd.DataFrame({
    "Validation Check": [
        "Invalid Quantity",
        "Invalid Unit Price",
        "Invalid Shipping Cost",
        "Invalid Discount",
        "Negative Sales",
        "Future Dates"
    ],
    "Records Found": [
        len(invalid_quantity),
        len(invalid_price),
        len(invalid_shipping),
        len(invalid_discount),
        len(invalid_sales),
        len(future_orders)
    ]
})

validation_summary

        Validation Check  Records Found
0       Invalid Quantity              0
1     Invalid Unit Price              0
2  Invalid Shipping Cost              0
3       Invalid Discount              0
4         Negative Sales              0
5           Future Dates              0

# Business Validation Summary

The dataset has been evaluated against key business rules commonly used in retail analytics. These validation checks improve data reliability and ensure that future analyses, dashboards, and machine learning models are built on trustworthy data.

# Export Clean Dataset

After completing all validation and cleaning steps, the cleaned dataset is exported for use in SQL analysis, exploratory data analysis (EDA), machine learning, and Power BI dashboard development.

In [135]:
# Export cleaned dataset

output_path = "../data/cleaned/cleaned_global_ecommerce_sales.csv"

df_clean.to_csv(output_path, index=False)

print(f"✅ Cleaned dataset exported successfully to:\n{output_path}")

✅ Cleaned dataset exported successfully to:
../data/cleaned/cleaned_global_ecommerce_sales.csv

In [136]:
# Verify cleaned dataset

cleaned_df = pd.read_csv(output_path)

cleaned_df.head()

,Order_ID,Order_Date,Customer_Name,Customer_Segment,Country,Region,Product_Category,Product_Name,Quantity,Unit_Price,Discount_Percent,Total_Sales,Shipping_Cost,Profit,Payment_Method
0,ORD-11121,2023-01-02,Karen Suzuki,Corporate,United States,North America,Technology,Wireless Bluetooth Headphones,3,99.43,0,298.29,9.31,124.92,Cash on Delivery
1,ORD-11244,2023-01-02,John Johansson,Corporate,Spain,Europe,Technology,Mechanical Gaming Keyboard,4,97.93,20,313.38,14.31,83.62,Cash on Delivery
2,ORD-10325,2023-01-03,Jessica Garcia,Consumer,Mexico,North America,Office Supplies,Binder Clips Assorted 48pc,2,10.74,0,21.48,8.12,3.69,Credit Card
3,ORD-10467,2023-01-03,Clara Taylor,Corporate,Italy,Europe,Technology,Webcam HD 1080p,2,61.86,15,105.16,10.79,26.32,PayPal
4,ORD-11454,2023-01-05,Felix Thomas,Consumer,Italy,Europe,Furniture,Standing Desk Converter,4,330.67,20,1058.14,11.09,253.44,Credit Card

# Business Observation

The cleaned dataset has been successfully exported and verified. This file will serve as the trusted source for SQL queries, exploratory data analysis, machine learning, and Power BI dashboard creation.

# Conclusion

The Data Cleaning phase has been successfully completed.

During this notebook, the dataset was systematically assessed and validated by:

- Evaluating overall data quality.
- Identifying missing values.
- Checking duplicate records.
- Validating data types.
- Applying business rule validations.
- Preparing a reliable analytical dataset.
- Exporting the cleaned dataset for future project phases.

The cleaned dataset is now ready for SQL analysis, exploratory data analysis (EDA), machine learning, and interactive Power BI dashboards.

# Next Phase

The next notebook focuses on **SQL Analysis**, where business questions will be answered using SQL queries to generate meaningful insights into sales performance, customer behavior, product performance, regional trends, and profitability.