# Feature Engineering

## Project
Bharat Bazaar Intelligence Platform

## Objective

Feature Engineering transforms cleaned business data into machine learning-ready features by creating new variables, extracting meaningful information, encoding categorical variables, and preparing the dataset for predictive modeling.

This notebook focuses on improving model performance through business-driven feature creation and data transformation techniques.

In [37]:
# Data Manipulation
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Display Settings
pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:.2f}".format)

print("Libraries imported successfully.")

Libraries imported successfully.

# Load Cleaned Dataset

The cleaned dataset generated in the Data Cleaning notebook is loaded for feature engineering.

In [38]:
df = pd.read_csv("../data/cleaned/cleaned_global_ecommerce_sales.csv")

df.head()

,Order_ID,Order_Date,Customer_Name,Customer_Segment,Country,Region,Product_Category,Product_Name,Quantity,Unit_Price,Discount_Percent,Total_Sales,Shipping_Cost,Profit,Payment_Method
0,ORD-11121,2023-01-02,Karen Suzuki,Corporate,United States,North America,Technology,Wireless Bluetooth Headphones,3,99.43,0,298.29,9.31,124.92,Cash on Delivery
1,ORD-11244,2023-01-02,John Johansson,Corporate,Spain,Europe,Technology,Mechanical Gaming Keyboard,4,97.93,20,313.38,14.31,83.62,Cash on Delivery
2,ORD-10325,2023-01-03,Jessica Garcia,Consumer,Mexico,North America,Office Supplies,Binder Clips Assorted 48pc,2,10.74,0,21.48,8.12,3.69,Credit Card
3,ORD-10467,2023-01-03,Clara Taylor,Corporate,Italy,Europe,Technology,Webcam HD 1080p,2,61.86,15,105.16,10.79,26.32,PayPal
4,ORD-11454,2023-01-05,Felix Thomas,Consumer,Italy,Europe,Furniture,Standing Desk Converter,4,330.67,20,1058.14,11.09,253.44,Credit Card

In [39]:
print("Shape :", df.shape)

print("\nData Types\n")
print(df.dtypes)

Shape : (2000, 15)

Data Types

Order_ID                str
Order_Date              str
Customer_Name           str
Customer_Segment        str
Country                 str
Region                  str
Product_Category        str
Product_Name            str
Quantity              int64
Unit_Price          float64
Discount_Percent      int64
Total_Sales         float64
Shipping_Cost       float64
Profit              float64
Payment_Method          str
dtype: object

# Dataset Verification

Before creating new features, the dataset is verified to ensure that all required variables are available and correctly formatted.

In [40]:
df.info()# Business Feature Creation

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          2000 non-null   str
 1   Order_Date        2000 non-null   str
 2   Customer_Name     2000 non-null   str
 3   Customer_Segment  2000 non-null   str
 4   Country           2000 non-null   str
 5   Region            2000 non-null   str
 6   Product_Category  2000 non-null   str
 7   Product_Name      2000 non-null   str
 8   Quantity          2000 non-null   int64
 9   Unit_Price        2000 non-null   float64
 10  Discount_Percent  2000 non-null   int64
 11  Total_Sales       2000 non-null   float64
 12  Shipping_Cost     2000 non-null   float64
 13  Profit            2000 non-null   float64
 14  Payment_Method    2000 non-null   str
dtypes: float64(4), int64(2), str(9)
memory usage: 440.1 KB

# Business Feature Creation

## Objective

Create meaningful business-driven features that improve machine learning performance and provide deeper business insights.

Rather than relying only on the original variables, new features are engineered to capture customer purchasing behavior, profitability, pricing strategy, and operational efficiency.

In [41]:
# Create a copy of the dataset
feature_df = df.copy()

feature_df.head()

,Order_ID,Order_Date,Customer_Name,Customer_Segment,Country,Region,Product_Category,Product_Name,Quantity,Unit_Price,Discount_Percent,Total_Sales,Shipping_Cost,Profit,Payment_Method
0,ORD-11121,2023-01-02,Karen Suzuki,Corporate,United States,North America,Technology,Wireless Bluetooth Headphones,3,99.43,0,298.29,9.31,124.92,Cash on Delivery
1,ORD-11244,2023-01-02,John Johansson,Corporate,Spain,Europe,Technology,Mechanical Gaming Keyboard,4,97.93,20,313.38,14.31,83.62,Cash on Delivery
2,ORD-10325,2023-01-03,Jessica Garcia,Consumer,Mexico,North America,Office Supplies,Binder Clips Assorted 48pc,2,10.74,0,21.48,8.12,3.69,Credit Card
3,ORD-10467,2023-01-03,Clara Taylor,Corporate,Italy,Europe,Technology,Webcam HD 1080p,2,61.86,15,105.16,10.79,26.32,PayPal
4,ORD-11454,2023-01-05,Felix Thomas,Consumer,Italy,Europe,Furniture,Standing Desk Converter,4,330.67,20,1058.14,11.09,253.44,Credit Card

## Feature 1 — Profit Margin (%)

Profit Margin measures the percentage of revenue retained as profit after each sale.

It is one of the most important business KPIs for profitability analysis.

In [42]:
feature_df["Profit_Margin"] = (
    feature_df["Profit"] / feature_df["Total_Sales"]
) * 100

feature_df["Profit_Margin"] = feature_df["Profit_Margin"].round(2)

feature_df[["Profit", "Total_Sales", "Profit_Margin"]].head()

   Profit  Total_Sales  Profit_Margin
0  124.92       298.29          41.88
1   83.62       313.38          26.68
2    3.69        21.48          17.18
3   26.32       105.16          25.03
4  253.44      1058.14          23.95

## Feature 2 — Revenue per Unit

Revenue per Unit measures the average revenue generated from each item sold.

This feature helps identify premium and low-value transactions.0

In [43]:
feature_df["Revenue_Per_Unit"] = (
    feature_df["Total_Sales"] /
    feature_df["Quantity"]
).round(2)

feature_df[
    ["Quantity",
     "Total_Sales",
     "Revenue_Per_Unit"]
].head()

   Quantity  Total_Sales  Revenue_Per_Unit
0         3       298.29             99.43
1         4       313.38             78.34
2         2        21.48             10.74
3         2       105.16             52.58
4         4      1058.14            264.54

## Feature 3 — Shipping Cost Ratio

Shipping Cost Ratio measures the percentage of sales consumed by shipping expenses.

This feature evaluates logistics efficiency.

In [44]:
feature_df["Shipping_Cost_Ratio"] = (
    feature_df["Shipping_Cost"] /
    feature_df["Total_Sales"]
) * 100

feature_df["Shipping_Cost_Ratio"] = (
    feature_df["Shipping_Cost_Ratio"]
    .round(2)
)

feature_df[
    ["Shipping_Cost",
     "Total_Sales",
     "Shipping_Cost_Ratio"]
].head()

   Shipping_Cost  Total_Sales  Shipping_Cost_Ratio
0           9.31       298.29                 3.12
1          14.31       313.38                 4.57
2           8.12        21.48                37.80
3          10.79       105.16                10.26
4          11.09      1058.14                 1.05

## Feature 4 — High Value Order

Orders with Total Sales greater than the dataset median are classified as High Value Orders.

This feature helps distinguish premium transactions.

In [45]:
median_sales = feature_df["Total_Sales"].median()

feature_df["High_Value_Order"] = np.where(
    feature_df["Total_Sales"] >= median_sales,
    1,
    0
)

feature_df[
    ["Total_Sales", "High_Value_Order"]
].head()

   Total_Sales  High_Value_Order
0       298.29                 1
1       313.38                 1
2        21.48                 0
3       105.16                 0
4      1058.14                 1

In [46]:
feature_df[
    [
        "Profit_Margin",
        "Revenue_Per_Unit",
        "Shipping_Cost_Ratio",
        "High_Value_Order"
    ]
].describe()

       Profit_Margin  Revenue_Per_Unit  Shipping_Cost_Ratio  High_Value_Order
count        2000.00           2000.00              2000.00           2000.00
mean           20.02             66.92                21.99              0.50
std            27.94             72.61                30.30              0.50
min          -417.36              2.42                 0.44              0.00
25%            15.32             17.18                 4.89              0.00
50%            28.29             41.88                10.55              0.50
75%            35.13             82.36                27.32              1.00
max            48.36            472.56               461.16              1.00

# Advanced Feature Engineering

## Objective

Create business-driven categorical features that capture customer purchasing behavior, pricing strategy, and profitability.

These engineered features improve model interpretability and predictive performance.

## Feature 5 — Order Size Category

Orders are classified into Small, Medium, and Large based on quantity purchased.

In [47]:
feature_df["Order_Size"] = pd.cut(
    feature_df["Quantity"],
    bins=[0, 3, 7, feature_df["Quantity"].max()],
    labels=["Small", "Medium", "Large"],
    include_lowest=True
)

feature_df[["Quantity", "Order_Size"]].head()

   Quantity Order_Size
0         3      Small
1         4     Medium
2         2      Small
3         2      Small
4         4     Medium

## Feature 6 — Price Category

Products are categorized into Budget, Standard, Premium, and Luxury based on Unit Price quartiles.

In [48]:
feature_df["Price_Category"] = pd.qcut(
    feature_df["Unit_Price"],
    q=4,
    labels=["Budget", "Standard", "Premium", "Luxury"]
)

feature_df[
    ["Unit_Price", "Price_Category"]
].head()

   Unit_Price Price_Category
0       99.43         Luxury
1       97.93         Luxury
2       10.74         Budget
3       61.86        Premium
4      330.67         Luxury

## Feature 7 — Discount Band

Discount percentages are grouped into business-friendly ranges.

In [49]:
feature_df["Discount_Band"] = pd.cut(
    feature_df["Discount_Percent"],
    bins=[-1, 5, 10, 20, 30],
    labels=[
        "Low",
        "Moderate",
        "High",
        "Very High"
    ]
)

feature_df[
    ["Discount_Percent", "Discount_Band"]
].head()

   Discount_Percent Discount_Band
0                 0           Low
1                20          High
2                 0           Low
3                15          High
4                20          High

## Feature 8 — Profit Category

Orders are classified into Low, Medium, and High Profit categories based on profit distribution.

In [50]:
feature_df["Profit_Category"] = pd.qcut(
    feature_df["Profit"],
    q=3,
    labels=[
        "Low Profit",
        "Medium Profit",
        "High Profit"
    ]
)

feature_df[
    ["Profit", "Profit_Category"]
].head()

   Profit Profit_Category
0  124.92     High Profit
1   83.62     High Profit
2    3.69      Low Profit
3   26.32   Medium Profit
4  253.44     High Profit

In [51]:
feature_df[
    [
        "Order_Size",
        "Price_Category",
        "Discount_Band",
        "Profit_Category"
    ]
].describe(include="all")

       Order_Size Price_Category Discount_Band Profit_Category
count        2000           2000          2000            2000
unique          3              4             4               3
top         Small         Budget           Low      Low Profit
freq         1211            500           991             668

In [52]:
categorical_features = [
    "Order_Size",
    "Price_Category",
    "Discount_Band",
    "Profit_Category"
]

for feature in categorical_features:
    print(f"\n{feature}")
    print(feature_df[feature].value_counts())

Order_Size
Order_Size
Small     1211
Medium     593
Large      196
Name: count, dtype: int64

Price_Category
Price_Category
Budget      500
Standard    500
Premium     500
Luxury      500
Name: count, dtype: int64

Discount_Band
Discount_Band
Low          991
High         481
Moderate     443
Very High     85
Name: count, dtype: int64

Profit_Category
Profit_Category
Low Profit       668
High Profit      667
Medium Profit    665
Name: count, dtype: int64

# Date & Time Feature Engineering

## Objective

Extract meaningful time-based features from the order date to capture seasonality, customer purchasing trends, and business cycles.

These features help machine learning models identify temporal patterns that influence sales and profitability.

## Feature 9 — Date Conversion

Convert the Order_Date column into datetime format for extracting additional calendar-based features.

In [53]:
feature_df["Order_Date"] = pd.to_datetime(feature_df["Order_Date"])

feature_df["Order_Date"].head()

0   2023-01-02
1   2023-01-02
2   2023-01-03
3   2023-01-03
4   2023-01-05
Name: Order_Date, dtype: datetime64[us]

## Feature 10 — Year

Extract the year of each order.

In [54]:
feature_df["Year"] = feature_df["Order_Date"].dt.year

feature_df[["Order_Date", "Year"]].head()

  Order_Date  Year
0 2023-01-02  2023
1 2023-01-02  2023
2 2023-01-03  2023
3 2023-01-03  2023
4 2023-01-05  2023

## Feature 11 — Month

Extract the month of each order to capture monthly purchasing trends.

In [55]:
feature_df["Month"] = feature_df["Order_Date"].dt.month

feature_df[["Order_Date", "Month"]].head()

  Order_Date  Month
0 2023-01-02      1
1 2023-01-02      1
2 2023-01-03      1
3 2023-01-03      1
4 2023-01-05      1

## Feature 12 — Quarter

Extract the financial quarter of each order.

In [56]:
feature_df["Quarter"] = feature_df["Order_Date"].dt.quarter

feature_df[["Order_Date", "Quarter"]].head()

  Order_Date  Quarter
0 2023-01-02        1
1 2023-01-02        1
2 2023-01-03        1
3 2023-01-03        1
4 2023-01-05        1

## Feature 13 — Day of Week

Extract the day of the week to analyze weekly purchasing behavior.

In [57]:
feature_df["Day_of_Week"] = feature_df["Order_Date"].dt.day_name()

feature_df[
    ["Order_Date", "Day_of_Week"]
].head()

  Order_Date Day_of_Week
0 2023-01-02      Monday
1 2023-01-02      Monday
2 2023-01-03     Tuesday
3 2023-01-03     Tuesday
4 2023-01-05    Thursday

## Feature 14 — Weekend Order

Identify whether an order was placed on a weekend.

In [58]:
feature_df["Weekend_Order"] = np.where(
    feature_df["Order_Date"].dt.weekday >= 5,
    1,
    0
)

feature_df[
    ["Order_Date", "Weekend_Order"]
].head()

  Order_Date  Weekend_Order
0 2023-01-02              0
1 2023-01-02              0
2 2023-01-03              0
3 2023-01-03              0
4 2023-01-05              0

In [59]:
feature_df[
    [
        "Year",
        "Month",
        "Quarter",
        "Day_of_Week",
        "Weekend_Order"
    ]
].describe(include="all")

          Year   Month  Quarter Day_of_Week  Weekend_Order
count  2000.00 2000.00  2000.00        2000        2000.00
unique     NaN     NaN      NaN           7            NaN
top        NaN     NaN      NaN     Tuesday            NaN
freq       NaN     NaN      NaN         308            NaN
mean   2024.01    6.82     2.61         NaN           0.30
std       0.82    3.39     1.10         NaN           0.46
min    2023.00    1.00     1.00         NaN           0.00
25%    2023.00    4.00     2.00         NaN           0.00
50%    2024.00    7.00     3.00         NaN           0.00
75%    2025.00   10.00     4.00         NaN           1.00
max    2025.00   12.00     4.00         NaN           1.00

In [60]:
print("Years Available:")
print(feature_df["Year"].value_counts().sort_index())

print("\nMonths Available:")
print(feature_df["Month"].value_counts().sort_index())

print("\nWeekend Orders:")
print(feature_df["Weekend_Order"].value_counts())

Years Available:
Year
2023    670
2024    649
2025    681
Name: count, dtype: int64

Months Available:
Month
1     138
2     128
3     143
4     182
5     174
6     167
7     170
8     162
9     178
10    205
11    162
12    191
Name: count, dtype: int64

Weekend Orders:
Weekend_Order
0    1409
1     591
Name: count, dtype: int64

# Categorical Feature Encoding

## Objective

Machine learning algorithms require numerical input. This section converts categorical variables into numerical representations while preserving meaningful business information.

Both Label Encoding and One-Hot Encoding are applied based on the nature of the variables.

In [61]:
# Create a copy for encoding
encoded_df = feature_df.copy()

encoded_df.head()

,Order_ID,Order_Date,Customer_Name,Customer_Segment,Country,Region,Product_Category,Product_Name,Quantity,Unit_Price,Discount_Percent,Total_Sales,Shipping_Cost,Profit,Payment_Method,Profit_Margin,Revenue_Per_Unit,Shipping_Cost_Ratio,High_Value_Order,Order_Size,Price_Category,Discount_Band,Profit_Category,Year,Month,Quarter,Day_of_Week,Weekend_Order
0,ORD-11121,2023-01-02,Karen Suzuki,Corporate,United States,North America,Technology,Wireless Bluetooth Headphones,3,99.43,0,298.29,9.31,124.92,Cash on Delivery,41.88,99.43,3.12,1,Small,Luxury,Low,High Profit,2023,1,1,Monday,0
1,ORD-11244,2023-01-02,John Johansson,Corporate,Spain,Europe,Technology,Mechanical Gaming Keyboard,4,97.93,20,313.38,14.31,83.62,Cash on Delivery,26.68,78.34,4.57,1,Medium,Luxury,High,High Profit,2023,1,1,Monday,0
2,ORD-10325,2023-01-03,Jessica Garcia,Consumer,Mexico,North America,Office Supplies,Binder Clips Assorted 48pc,2,10.74,0,21.48,8.12,3.69,Credit Card,17.18,10.74,37.80,0,Small,Budget,Low,Low Profit,2023,1,1,Tuesday,0
3,ORD-10467,2023-01-03,Clara Taylor,Corporate,Italy,Europe,Technology,Webcam HD 1080p,2,61.86,15,105.16,10.79,26.32,PayPal,25.03,52.58,10.26,0,Small,Premium,High,Medium Profit,2023,1,1,Tuesday,0
4,ORD-11454,2023-01-05,Felix Thomas,Consumer,Italy,Europe,Furniture,Standing Desk Converter,4,330.67,20,1058.14,11.09,253.44,Credit Card,23.95,264.54,1.05,1,Medium,Luxury,High,High Profit,2023,1,1,Thursday,0

## Label Encoding

Ordinal and engineered categorical features are encoded using Label Encoding.

In [62]:
encoded_df = feature_df.copy()

encoded_df.head()

,Order_ID,Order_Date,Customer_Name,Customer_Segment,Country,Region,Product_Category,Product_Name,Quantity,Unit_Price,Discount_Percent,Total_Sales,Shipping_Cost,Profit,Payment_Method,Profit_Margin,Revenue_Per_Unit,Shipping_Cost_Ratio,High_Value_Order,Order_Size,Price_Category,Discount_Band,Profit_Category,Year,Month,Quarter,Day_of_Week,Weekend_Order
0,ORD-11121,2023-01-02,Karen Suzuki,Corporate,United States,North America,Technology,Wireless Bluetooth Headphones,3,99.43,0,298.29,9.31,124.92,Cash on Delivery,41.88,99.43,3.12,1,Small,Luxury,Low,High Profit,2023,1,1,Monday,0
1,ORD-11244,2023-01-02,John Johansson,Corporate,Spain,Europe,Technology,Mechanical Gaming Keyboard,4,97.93,20,313.38,14.31,83.62,Cash on Delivery,26.68,78.34,4.57,1,Medium,Luxury,High,High Profit,2023,1,1,Monday,0
2,ORD-10325,2023-01-03,Jessica Garcia,Consumer,Mexico,North America,Office Supplies,Binder Clips Assorted 48pc,2,10.74,0,21.48,8.12,3.69,Credit Card,17.18,10.74,37.80,0,Small,Budget,Low,Low Profit,2023,1,1,Tuesday,0
3,ORD-10467,2023-01-03,Clara Taylor,Corporate,Italy,Europe,Technology,Webcam HD 1080p,2,61.86,15,105.16,10.79,26.32,PayPal,25.03,52.58,10.26,0,Small,Premium,High,Medium Profit,2023,1,1,Tuesday,0
4,ORD-11454,2023-01-05,Felix Thomas,Consumer,Italy,Europe,Furniture,Standing Desk Converter,4,330.67,20,1058.14,11.09,253.44,Credit Card,23.95,264.54,1.05,1,Medium,Luxury,High,High Profit,2023,1,1,Thursday,0

In [63]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

label_columns = [
    "Order_Size",
    "Price_Category",
    "Discount_Band",
    "Profit_Category"
]

for col in label_columns:
    encoded_df[col] = label_encoder.fit_transform(encoded_df[col])

encoded_df[label_columns].head()

   Order_Size  Price_Category  Discount_Band  Profit_Category
0           2               1              1                0
1           1               1              0                0
2           2               0              1                1
3           2               2              0                2
4           1               1              0                0

In [64]:
one_hot_columns = [
    "Customer_Segment",
    "Region",
    "Country",
    "Product_Category",
    "Payment_Method",
    "Day_of_Week"
]

encoded_df = pd.get_dummies(
    encoded_df,
    columns=one_hot_columns,
    drop_first=True,
    dtype=int
)

encoded_df.head()

,Order_ID,Order_Date,Customer_Name,Product_Name,Quantity,Unit_Price,Discount_Percent,Total_Sales,Shipping_Cost,Profit,Profit_Margin,Revenue_Per_Unit,Shipping_Cost_Ratio,High_Value_Order,Order_Size,Price_Category,Discount_Band,Profit_Category,Year,Month,Quarter,Weekend_Order,Customer_Segment_Corporate,Customer_Segment_Home Office,Region_Europe,Region_Middle East & Africa,Region_North America,Region_South America,Country_Australia,Country_Brazil,Country_Canada,Country_China,Country_Colombia,Country_France,Country_Germany,Country_India,Country_Italy,Country_Japan,Country_Mexico,Country_Nigeria,Country_Saudi Arabia,Country_South Africa,Country_South Korea,Country_Spain,Country_UAE,Country_United Kingdom,Country_United States,Product_Category_Furniture,Product_Category_Office Supplies,Product_Category_Technology,Payment_Method_Cash on Delivery,Payment_Method_Credit Card,Payment_Method_PayPal,Day_of_Week_Monday,Day_of_Week_Saturday,Day_of_Week_Sunday,Day_of_Week_Thursday,Day_of_Week_Tuesday,Day_of_Week_Wednesday
0,ORD-11121,2023-01-02,Karen Suzuki,Wireless Bluetooth Headphones,3,99.43,0,298.29,9.31,124.92,41.88,99.43,3.12,1,2,1,1,0,2023,1,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,0,0,0,0,0
1,ORD-11244,2023-01-02,John Johansson,Mechanical Gaming Keyboard,4,97.93,20,313.38,14.31,83.62,26.68,78.34,4.57,1,1,1,0,0,2023,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0
2,ORD-10325,2023-01-03,Jessica Garcia,Binder Clips Assorted 48pc,2,10.74,0,21.48,8.12,3.69,17.18,10.74,37.80,0,2,0,1,1,2023,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0
3,ORD-10467,2023-01-03,Clara Taylor,Webcam HD 1080p,2,61.86,15,105.16,10.79,26.32,25.03,52.58,10.26,0,2,2,0,2,2023,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0
4,ORD-11454,2023-01-05,Felix Thomas,Standing Desk Converter,4,330.67,20,1058.14,11.09,253.44,23.95,264.54,1.05,1,1,1,0,0,2023,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0

In [65]:
print("Dataset Shape After Encoding:")
print(encoded_df.shape)

Dataset Shape After Encoding:
(2000, 59)

In [66]:
print("Missing Values After Encoding:")
print(encoded_df.isnull().sum().sum())

Missing Values After Encoding:
0

In [67]:
from sklearn.preprocessing import StandardScaler

scaled_df = encoded_df.copy()

In [68]:
from sklearn.preprocessing import StandardScaler

scaled_df = encoded_df.copy()

scale_columns = [
    "Quantity",
    "Unit_Price",
    "Discount_Percent",
    "Total_Sales",
    "Shipping_Cost",
    "Profit",
    "Profit_Margin",
    "Revenue_Per_Unit",
    "Shipping_Cost_Ratio"
]

scaler = StandardScaler()

scaled_df[scale_columns] = scaler.fit_transform(
    scaled_df[scale_columns]
)

scaled_df[scale_columns].head()

,Quantity,Unit_Price,Discount_Percent,Total_Sales,Shipping_Cost,Profit,Profit_Margin,Revenue_Per_Unit,Shipping_Cost_Ratio
0,-0.21,0.33,-1.18,0.15,-0.69,0.33,0.78,0.45,-0.62
1,0.16,0.31,1.57,0.19,0.27,0.03,0.24,0.16,-0.57
2,-0.58,-0.79,-1.18,-0.58,-0.92,-0.55,-0.10,-0.77,0.52
3,-0.58,-0.14,0.89,-0.36,-0.40,-0.39,0.18,-0.20,-0.39
4,0.16,3.25,1.57,2.13,-0.35,1.27,0.14,2.72,-0.69

In [69]:
scaled_df[scale_columns].describe().T

                      count  mean  std    min   25%   50%  75%   max
Quantity            2000.00 -0.00 1.00  -0.95 -0.58 -0.21 0.53  4.23
Unit_Price          2000.00  0.00 1.00  -0.89 -0.69 -0.34 0.21  5.03
Discount_Percent    2000.00  0.00 1.00  -1.18 -1.18  0.20 0.89  2.95
Total_Sales         2000.00  0.00 1.00  -0.63 -0.53 -0.34 0.06  9.34
Shipping_Cost       2000.00  0.00 1.00  -1.41 -0.66 -0.20 0.39  5.27
Profit              2000.00  0.00 1.00  -0.66 -0.53 -0.34 0.08  9.41
Profit_Margin       2000.00  0.00 1.00 -15.66 -0.17  0.30 0.54  1.01
Revenue_Per_Unit    2000.00  0.00 1.00  -0.89 -0.69 -0.35 0.21  5.59
Shipping_Cost_Ratio 2000.00  0.00 1.00  -0.71 -0.56 -0.38 0.18 14.50

In [70]:
import joblib
import os

os.makedirs("../models", exist_ok=True)

joblib.dump(scaler, "../models/standard_scaler.pkl")

print("✅ Standard Scaler saved successfully.")

✅ Standard Scaler saved successfully.

In [71]:
os.makedirs("../data/processed", exist_ok=True)

scaled_df.to_csv(
    "../data/processed/ml_ready_dataset.csv",
    index=False
)

print("✅ ML-ready dataset saved successfully.")
print("Final Dataset Shape:", scaled_df.shape)

✅ ML-ready dataset saved successfully.
Final Dataset Shape: (2000, 59)

In [72]:
print("=" * 50)
print("ML READY DATASET SUMMARY")
print("=" * 50)

print("Rows:", scaled_df.shape[0])
print("Columns:", scaled_df.shape[1])
print("Missing Values:", scaled_df.isnull().sum().sum())
print("Duplicate Rows:", scaled_df.duplicated().sum())

print("\nTarget Variable Statistics:")
print(scaled_df["Profit"].describe())

==================================================
ML READY DATASET SUMMARY
==================================================
Rows: 2000
Columns: 59
Missing Values: 0
Duplicate Rows: 0

Target Variable Statistics:
count   2000.00
mean       0.00
std        1.00
min       -0.66
25%       -0.53
50%       -0.34
75%        0.08
max        9.41
Name: Profit, dtype: float64

# Conclusion

Feature Engineering has been successfully completed for the Bharat Bazaar Intelligence Platform.

The dataset has been enriched with business-oriented features, categorical variables have been encoded, numerical features have been standardized, and the final machine learning-ready dataset has been created.

Key Achievements:

- Created meaningful business features
- Performed label encoding and one-hot encoding
- Applied feature scaling using StandardScaler
- Validated data quality by checking missing values and duplicates
- Exported the final ML-ready dataset
- Saved the trained StandardScaler for future predictions

The processed dataset is now ready for machine learning model development and evaluation.